name: test

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        rust: ["stable"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - name: Lint
        run: |
          cargo clippy
          cargo fmt --check
      - name: Test
        run: cargo test
      - name: Security
        run: |
          cargo install cargo-audit
          cargo audit
      - name: Build
        run: cargo build --release
